[tool.poetry]
name = "llm-zoomcamp"
version = "0.1.0"
description = "LLM Zoomcamp course repo"
authors = ["Yauheni-Khvainitski <euheniy.khvoinitski@gmail.com>"]
readme = "README.md"
repository = "https://github.com/Yauheni-Khvainitski/llm-zoomcamp.git"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
notebook = "7.1.2"
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
