[tool.poetry]
name = "llm-zoomcamp"
version = "0.1.0"
description = "LLM Zoomcamp course repo"
authors = ["Yauheni-Khvainitski <euheniy.khvoinitski@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
